authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.user_register, name='user_register'),
    path('user/profile/', authapp.user_profile, name='user_profile'),
]

homkashop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from homkashop import settings

urlpatterns = [
    path('', include('mainapp.urls', namespace='main')),
    path('auth/', include('authapp.urls', namespace='auth')),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contact, name='contact'),
]

authapp/models.py
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    pass

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя категории', max_length=128)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return f'{self.name}'

class Product(models.Model):
    category = models.ForeignKey(ProductCategory,
                                 on_delete=models.CASCADE,
                                 verbose_name='категория продукта')
    name = models.CharField('имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField('краткое описание продукта', max_length=64, blank=True)
    description = models.TextField('описание продукта', blank=True)
    price = models.DecimalField('цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    # is_active = models.BooleanField(default=True)
    #
    def __str__(self):
        return f'{self.name} ({self.category.name})'
    #
    # class Meta:
    #     verbose_name = 'продукт'
    #     verbose_name_plural = 'продукты'

authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from authapp.models import ShopUser


class ShopUserAuthenticationForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'password1', 'password1')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class ShopUserProfileForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'

authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import ShopUserAuthenticationForm, ShopUserRegisterForm, ShopUserProfileForm


def login(request):
    if request.method == 'POST':
        form = ShopUserAuthenticationForm(data=request.POST)
        if form.is_valid():  # errors dict
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = ShopUserAuthenticationForm()
    context = {
        'page_title': 'аутентификация',
        'form': form
    }
    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def user_register(request):
    form = ShopUserRegisterForm()
    context = {
        'page_title': 'регистрация',
        'form': form
    }
    return render(request, 'authapp/login.html', context)


def user_profile(request):
    form = ShopUserProfileForm()
    context = {
        'page_title': 'профиль',
        'form': form
    }
    return render(request, 'authapp/login.html', context)

mainapp/views.py
from django.shortcuts import render
from datetime import datetime
from mainapp.models import ProductCategory


def index(request):
    context = {
        'page_title' : 'главная',
        # 'datetime': datetime.now(),
    }
    return render(request, 'mainapp/index.html', context)


def products(request):
    categories = ProductCategory.objects.all()
    context = {
        'page_title': 'каталог',
        'categories': categories,
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': '+7-999-888-77-77',
            'email': 'info@homkashop.ru',
            'address': 'В пределах МКАД',

        },
        {
            'city': 'Санкт-Петербург',
            'phone': '+7-777-888-99-99',
            'email': 'info@homkashop.ru',
            'address': 'В пределах КАД',

        },
    ]
    context = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contact.html', context)

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat+Alternates:wght@400;500&display=swap"
          rel="stylesheet">
    <title>{{ page_title|title }}</title>
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>

<header class="header">
    <div class="container">
        <div class="header_inner">
            <div class="header_logo">hOmka</div>
            <nav class="nav">
                <a class="nav_link active" href="{% url 'main:index' %}">домой</a>
                <a class="nav_link" href="{% url 'main:products' %}">продукты</a>
                <a class="nav_link" href="{% url 'main:contact' %}">контакты</a></nav>
        </div>
    </div>
    {% block header_menu %}
    {% endblock %}
</header>

{% block intro %}

{% endblock %}

<div class="container">
    <div class="login">
        <div class="h2 text-center head">
            Вход в систему
        </div>
        {% block container %}
        {% endblock %}
    </div>
</div>

</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}


{% block container %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" class="form-control" value="войти">
    </form>
    <a href="{#% url 'auth:user_register' %#}"
       class="btn btn-round form-control">
          зарегистрироваться
    </a>
{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat+Alternates:wght@400;500&display=swap"
          rel="stylesheet">
    <title>{{ page_title|title }}</title>
    {% block css %}
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>

<body>

<header class="header">
    <div class="container">
        <div class="header_inner">
            <div class="header_logo">hOmka</div>
            <nav class="nav">
                <a class="nav_link active" href="{% url 'main:index' %}">домой</a>
                <a class="nav_link" href="{% url 'main:products' %}">продукты</a>
                <a class="nav_link" href="{% url 'main:contact' %}">контакты</a></nav>
        </div>
    </div>
    {% block header_menu %}
    {% endblock %}
</header>

{% block intro %}

{% endblock %}

<div class="footer">
    <p>&copy; Все права защищены</p>
    <!--{{ datetime }}-->
    {% now "d.m.Y" %}
</div>

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}

{% block intro %}
<div class="intro_product">
    <div class="container">
        <div class="location">

            {% for item in locations %}
            <h4>{{item.city }}</h4>
            <div class="contacts">
                <h5>Телефон</h5>
                <p>{{ item.phone }}</p>
            </div>
            <div class="contacts">
                <h5>Email</h5>
                <p>{{ item.phone }}</p>
            </div>
            <div class="contacts">
                <h5>Адрес</h5>
                <p>{{ item.phone  }}</p>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}

{% block intro %}
<div class="intro">
    <div class="container">
        <div class="intro_inner">
            <h1 class="intro_title">Добро пожаловать в мир моды</h1>
            <a class="intro_inner_btn" href="#"> Начать покупки </a>
        </div>
    </div>
</div>
{% endblock %}

<!--
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&family=Montserrat+Alternates:wght@400;500&display=swap" rel="stylesheet">
    <title>Shop</title>
    <link rel="stylesheet" type="text/css" href="static/css/style.css">
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="header_inner">
                <div class="header_logo">hOmka</div>
                <nav class="nav"> <a class="nav_link active" href="/" >домой</a> <a class="nav_link" href="/products/">продукты</a> <a class="nav_link" href="/contact/">контакты</a> </nav>
            </div>
        </div>
    </header>
    <div class="intro">
        <div class="container">
            <div class="intro_inner">
                <h1 class="intro_title">Добро пожаловать в мир моды</h1>
                <a class="intro_inner_btn" href="#"> Начать покупки </a>
            </div>
        </div>
    </div>
    <div class="footer">
        <p>&copy; Все права защищены</p>
    </div>
</body>

</html>
-->

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block header_menu %}
<div class="header_menu">
    <nav class="nav_menu">
        {% for category in categories %}
            <a class="nav_link_menu" href="#">{{ category.name }}</a>
        {% endfor %}
</div>
{% endblock %}


{% block intro %}
<div class="intro_product">
    <div class="product_foto"><img src="{% static 'img/orange_sweater.jpg' %}" alt="" width="300px"></div>
    <div class="product_desscription">
        <h1>Оранжевая водолазка</h1>
        <p class="detailed_description">Водолазка выполнена из высококачественного трикотажа.
            <br> Оранжевый цвет создаёт яркий современный стиль </p>
        <h3>Детали:</h3>
        <p> Сезон: мульти
            <br> Страна производства: Китай </p> <a href="#" class="red-button">
        заказать
    </a></div>
</div>
{% endblock %}